import example from "./robotPickPlace.json";
import type { SceneDocument } from "../scene";
import type { MeshPayload } from "../types";

/** Generated by scripts/examples/robot_pick_place.py; no backend required. */
export const robotPickPlaceExample = example as unknown as { document: SceneDocument; meshes: MeshPayload[] };
